Repository slowy07/luna, pull requests merged in 2022-11, with the labels that each got.

#8 add: rules contributing guidelines
  CONTRIBUTING.md
Labels: add

#9 fix: fixing even more typos on contributing.md
  CONTRIBUTING.md
Labels: bug

#10 docs: fixed typo in readme.md
  README.md
Labels: documentation

#11 docs: added breaking change
  CONTRIBUTING.md
Labels: documentation

#13 feat: feature update on luna
  .github/pull_request_template.md
  CITATION.cff
  CONTRIBUTING.md
  stable_diffusion_tensorflow/clip_tokenizer/__init__.py
Labels: enhancement

#15 docs: new prompt, changed readme, upload image, rename image
  .github/result_output/anime_street_ilustration.png
  .github/result_output/minimalist_house_with_family_mountainous_forested_wild_concept_art_illustration.png
  .github/result_output/natural_cave.png
  .github/workflows/pythonPostProcessing.yml
  README.md
  demo_prompt.txt
Labels: documentation
